### PR TITLE
Moved to Fetch 2

### PR DESCRIPTION
**Pull request by rockResolve**
Based on @alfkonee's work. #28 

Added:
- fix for passing withDefaults({credentials: ...
- fix for passing params / breeze.Query.withParameters
- fix for returning status
- complete removal of all aurelia-http-client
- rewrite of ajax-adapter tests for fetch
  (including removal of jasmine.Ajax)

### CODE REVIEW

**Comment by rockResolve** [comment]
A couple of issues to resolve.

I commented out the window.CustomEvent polyfill at the start of ajax-adapter.spec.js.
Cant see any reason why this was/is needed.

I also commented out the last test: 'handles null response'.
Fetch does not cope with a null response, but when would a null response ever be a valid?
Breeze returns a response with a type even when an empty dataset is returned.

**Comment by jdanyow** [comment]
@rockResolve awesome!

> I commented out the window.CustomEvent polyfill at the start of ajax-adapter.spec.js.
> Can't see any reason why this was/is needed.

I don't remember why that was there.

> I also commented out the last test: 'handles null response'.
> Fetch does not cope with a null response, but when would a null response ever be a valid?
> Breeze returns a response with a type even when an empty dataset is returned.

I think this is a relic from the initial port from one of the ajax adapters that ships with breeze.  Safe to remove.

---

I'll get this merged asap

**Comment by rockResolve** [comment]
Thanks @jdanyow
Some notes that maybe we should document (and avoid the traps I found!)
- Because this change uses aurelia-fetch, so it has the same requirements to support IE - a fetch polyfill is required.
- Should configure the fetch HttpClient as per aurelia-fetch notes e.g.`fetchHttp.configure(config => { config.useStandardConfiguration()`
- Also maybe a warning that because aurelia DI by default gets a single instance, need to be careful there are no conflicts with other users of the fetch HttpClient e.g. the skeleton users view model sets the base url to 'https://api.github.com/'

**Comment by jdanyow** [comment]
Thanks @rockResolve.  I'm going to integrate this change into one of my projects, get everything working and then publish a new build of aurelia-breeze to npm and github releases

**Comment by rockResolve** [comment]
Fantastic.

**Pull request merged**
